language: ruby
script:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
#- .forge-releng/publish
rvm:
  - 1.8.7
  - 1.9.3-p484
  - 2.0.0
bundler_args: --without system_tests
env:
  - PUPPET_VERSION=4.4.1
  - PUPPET_VERSION=3.7.3
  - PUPPET_VERSION=3.6.0
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.4.2
  - PUPPET_VERSION=3.3.1
  - PUPPET_VERSION=3.2.3
  - PUPPET_VERSION=2.7.21
matrix:
  exclude:
   - rvm: 1.8.7
     env: PUPPET_VERSION=4.4.1
   - rvm: 2.0.0
     env: PUPPET_VERSION=2.7.21
